### ISSUE TITLE
Organizer field in Event model needs to default to the user creating the event

### ISSUE THREAD

**Issue by stfinney** [stfinney/ffx#1]
The Organizer field was originally just set as a foreign key field, which meant the admin form provided a drop down selector with the options being all the registered users. This is not ideal, as the author of an event would have to find themselves on a potentially long list, and it also leaves it open to malicious mis-attribution of events. Currently, the field is set to non-editable to avoid this issue, but what it really needs is to default to the current user when they create an event (and still be non-editable, so there's no room for mistakes or deliberate mis-attribution).

**Comment by sorenchr** [comment]
This is going to be part of the logic on the event create page.
