### ISSUE TITLE
Event creation page

### ISSUE THREAD

**Issue by stfinney** [stfinney/ffx#8]

**Comment by sorenchr** [comment]
Backbone of event creation is done, waiting for HTML template

**Comment by sorenchr** [comment]
Almost done, we just need to figure out what to do with address lookups. Should we let the user choose the address on a map?

**Comment by joseph5wu** [comment]
Did you figure out how to upload an image, too?

**Comment by sorenchr** [comment]
Yes, the image upload should work as well.

On Monday, 7 December 2015, joseph5wu notifications@github.com wrote:

> Did you figure out how to upload an image, too?
> 
> > On Dec 7, 2015, at 1:03 AM, Søren Christensen <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > Almost done, we just need to figure out what to do with address lookups.
> > Should we let the user choose the address on a map?
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/stfinney/ffx/issues/8#issuecomment-162453566>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stfinney/ffx/issues/8#issuecomment-162454182.

## 

Med venlig hilsen

Søren Qvist Christensen

**Comment by sorenchr** [comment]
Done.
